package cn.g_open.net_worm.db.mapper;

import cn.g_open.net_worm.db.model.IpInfo;
import cn.g_open.net_worm.db.model.IpInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int countByExample(IpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int deleteByExample(IpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int insert(IpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int insertSelective(IpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    List<IpInfo> selectByExample(IpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    IpInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") IpInfo record, @Param("example") IpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int updateByExample(@Param("record") IpInfo record, @Param("example") IpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int updateByPrimaryKeySelective(IpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    int updateByPrimaryKey(IpInfo record);
}