package cn.g_open.net_worm.db.model;

import java.util.Date;

public class IpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.id
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.startIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer startIp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.startIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer startIp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.startIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer startIp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.startIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer startIp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.endIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer endIp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.endIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer endIp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.endIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer endIp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.endIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Integer endIp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.location
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.createBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.createDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.modifyBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_worm_ip_info.modifyDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.id
     *
     * @return the value of net_worm_ip_info.id
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.id
     *
     * @param id the value for net_worm_ip_info.id
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.startIp1
     *
     * @return the value of net_worm_ip_info.startIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getStartIp1() {
        return startIp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.startIp1
     *
     * @param startIp1 the value for net_worm_ip_info.startIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setStartIp1(Integer startIp1) {
        this.startIp1 = startIp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.startIp2
     *
     * @return the value of net_worm_ip_info.startIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getStartIp2() {
        return startIp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.startIp2
     *
     * @param startIp2 the value for net_worm_ip_info.startIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setStartIp2(Integer startIp2) {
        this.startIp2 = startIp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.startIp3
     *
     * @return the value of net_worm_ip_info.startIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getStartIp3() {
        return startIp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.startIp3
     *
     * @param startIp3 the value for net_worm_ip_info.startIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setStartIp3(Integer startIp3) {
        this.startIp3 = startIp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.startIp4
     *
     * @return the value of net_worm_ip_info.startIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getStartIp4() {
        return startIp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.startIp4
     *
     * @param startIp4 the value for net_worm_ip_info.startIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setStartIp4(Integer startIp4) {
        this.startIp4 = startIp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.endIp1
     *
     * @return the value of net_worm_ip_info.endIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getEndIp1() {
        return endIp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.endIp1
     *
     * @param endIp1 the value for net_worm_ip_info.endIp1
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setEndIp1(Integer endIp1) {
        this.endIp1 = endIp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.endIp2
     *
     * @return the value of net_worm_ip_info.endIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getEndIp2() {
        return endIp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.endIp2
     *
     * @param endIp2 the value for net_worm_ip_info.endIp2
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setEndIp2(Integer endIp2) {
        this.endIp2 = endIp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.endIp3
     *
     * @return the value of net_worm_ip_info.endIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getEndIp3() {
        return endIp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.endIp3
     *
     * @param endIp3 the value for net_worm_ip_info.endIp3
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setEndIp3(Integer endIp3) {
        this.endIp3 = endIp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.endIp4
     *
     * @return the value of net_worm_ip_info.endIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Integer getEndIp4() {
        return endIp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.endIp4
     *
     * @param endIp4 the value for net_worm_ip_info.endIp4
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setEndIp4(Integer endIp4) {
        this.endIp4 = endIp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.location
     *
     * @return the value of net_worm_ip_info.location
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.location
     *
     * @param location the value for net_worm_ip_info.location
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.createBy
     *
     * @return the value of net_worm_ip_info.createBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.createBy
     *
     * @param createBy the value for net_worm_ip_info.createBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.createDate
     *
     * @return the value of net_worm_ip_info.createDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.createDate
     *
     * @param createDate the value for net_worm_ip_info.createDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.modifyBy
     *
     * @return the value of net_worm_ip_info.modifyBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.modifyBy
     *
     * @param modifyBy the value for net_worm_ip_info.modifyBy
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_worm_ip_info.modifyDate
     *
     * @return the value of net_worm_ip_info.modifyDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_worm_ip_info.modifyDate
     *
     * @param modifyDate the value for net_worm_ip_info.modifyDate
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}