package cn.g_open.net_worm.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IpInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public IpInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStartIp1IsNull() {
            addCriterion("startIp1 is null");
            return (Criteria) this;
        }

        public Criteria andStartIp1IsNotNull() {
            addCriterion("startIp1 is not null");
            return (Criteria) this;
        }

        public Criteria andStartIp1EqualTo(Integer value) {
            addCriterion("startIp1 =", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1NotEqualTo(Integer value) {
            addCriterion("startIp1 <>", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1GreaterThan(Integer value) {
            addCriterion("startIp1 >", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1GreaterThanOrEqualTo(Integer value) {
            addCriterion("startIp1 >=", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1LessThan(Integer value) {
            addCriterion("startIp1 <", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1LessThanOrEqualTo(Integer value) {
            addCriterion("startIp1 <=", value, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1In(List<Integer> values) {
            addCriterion("startIp1 in", values, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1NotIn(List<Integer> values) {
            addCriterion("startIp1 not in", values, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1Between(Integer value1, Integer value2) {
            addCriterion("startIp1 between", value1, value2, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp1NotBetween(Integer value1, Integer value2) {
            addCriterion("startIp1 not between", value1, value2, "startIp1");
            return (Criteria) this;
        }

        public Criteria andStartIp2IsNull() {
            addCriterion("startIp2 is null");
            return (Criteria) this;
        }

        public Criteria andStartIp2IsNotNull() {
            addCriterion("startIp2 is not null");
            return (Criteria) this;
        }

        public Criteria andStartIp2EqualTo(Integer value) {
            addCriterion("startIp2 =", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2NotEqualTo(Integer value) {
            addCriterion("startIp2 <>", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2GreaterThan(Integer value) {
            addCriterion("startIp2 >", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2GreaterThanOrEqualTo(Integer value) {
            addCriterion("startIp2 >=", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2LessThan(Integer value) {
            addCriterion("startIp2 <", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2LessThanOrEqualTo(Integer value) {
            addCriterion("startIp2 <=", value, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2In(List<Integer> values) {
            addCriterion("startIp2 in", values, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2NotIn(List<Integer> values) {
            addCriterion("startIp2 not in", values, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2Between(Integer value1, Integer value2) {
            addCriterion("startIp2 between", value1, value2, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp2NotBetween(Integer value1, Integer value2) {
            addCriterion("startIp2 not between", value1, value2, "startIp2");
            return (Criteria) this;
        }

        public Criteria andStartIp3IsNull() {
            addCriterion("startIp3 is null");
            return (Criteria) this;
        }

        public Criteria andStartIp3IsNotNull() {
            addCriterion("startIp3 is not null");
            return (Criteria) this;
        }

        public Criteria andStartIp3EqualTo(Integer value) {
            addCriterion("startIp3 =", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3NotEqualTo(Integer value) {
            addCriterion("startIp3 <>", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3GreaterThan(Integer value) {
            addCriterion("startIp3 >", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3GreaterThanOrEqualTo(Integer value) {
            addCriterion("startIp3 >=", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3LessThan(Integer value) {
            addCriterion("startIp3 <", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3LessThanOrEqualTo(Integer value) {
            addCriterion("startIp3 <=", value, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3In(List<Integer> values) {
            addCriterion("startIp3 in", values, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3NotIn(List<Integer> values) {
            addCriterion("startIp3 not in", values, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3Between(Integer value1, Integer value2) {
            addCriterion("startIp3 between", value1, value2, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp3NotBetween(Integer value1, Integer value2) {
            addCriterion("startIp3 not between", value1, value2, "startIp3");
            return (Criteria) this;
        }

        public Criteria andStartIp4IsNull() {
            addCriterion("startIp4 is null");
            return (Criteria) this;
        }

        public Criteria andStartIp4IsNotNull() {
            addCriterion("startIp4 is not null");
            return (Criteria) this;
        }

        public Criteria andStartIp4EqualTo(Integer value) {
            addCriterion("startIp4 =", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4NotEqualTo(Integer value) {
            addCriterion("startIp4 <>", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4GreaterThan(Integer value) {
            addCriterion("startIp4 >", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4GreaterThanOrEqualTo(Integer value) {
            addCriterion("startIp4 >=", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4LessThan(Integer value) {
            addCriterion("startIp4 <", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4LessThanOrEqualTo(Integer value) {
            addCriterion("startIp4 <=", value, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4In(List<Integer> values) {
            addCriterion("startIp4 in", values, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4NotIn(List<Integer> values) {
            addCriterion("startIp4 not in", values, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4Between(Integer value1, Integer value2) {
            addCriterion("startIp4 between", value1, value2, "startIp4");
            return (Criteria) this;
        }

        public Criteria andStartIp4NotBetween(Integer value1, Integer value2) {
            addCriterion("startIp4 not between", value1, value2, "startIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp1IsNull() {
            addCriterion("endIp1 is null");
            return (Criteria) this;
        }

        public Criteria andEndIp1IsNotNull() {
            addCriterion("endIp1 is not null");
            return (Criteria) this;
        }

        public Criteria andEndIp1EqualTo(Integer value) {
            addCriterion("endIp1 =", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1NotEqualTo(Integer value) {
            addCriterion("endIp1 <>", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1GreaterThan(Integer value) {
            addCriterion("endIp1 >", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1GreaterThanOrEqualTo(Integer value) {
            addCriterion("endIp1 >=", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1LessThan(Integer value) {
            addCriterion("endIp1 <", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1LessThanOrEqualTo(Integer value) {
            addCriterion("endIp1 <=", value, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1In(List<Integer> values) {
            addCriterion("endIp1 in", values, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1NotIn(List<Integer> values) {
            addCriterion("endIp1 not in", values, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1Between(Integer value1, Integer value2) {
            addCriterion("endIp1 between", value1, value2, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp1NotBetween(Integer value1, Integer value2) {
            addCriterion("endIp1 not between", value1, value2, "endIp1");
            return (Criteria) this;
        }

        public Criteria andEndIp2IsNull() {
            addCriterion("endIp2 is null");
            return (Criteria) this;
        }

        public Criteria andEndIp2IsNotNull() {
            addCriterion("endIp2 is not null");
            return (Criteria) this;
        }

        public Criteria andEndIp2EqualTo(Integer value) {
            addCriterion("endIp2 =", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2NotEqualTo(Integer value) {
            addCriterion("endIp2 <>", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2GreaterThan(Integer value) {
            addCriterion("endIp2 >", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2GreaterThanOrEqualTo(Integer value) {
            addCriterion("endIp2 >=", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2LessThan(Integer value) {
            addCriterion("endIp2 <", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2LessThanOrEqualTo(Integer value) {
            addCriterion("endIp2 <=", value, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2In(List<Integer> values) {
            addCriterion("endIp2 in", values, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2NotIn(List<Integer> values) {
            addCriterion("endIp2 not in", values, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2Between(Integer value1, Integer value2) {
            addCriterion("endIp2 between", value1, value2, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp2NotBetween(Integer value1, Integer value2) {
            addCriterion("endIp2 not between", value1, value2, "endIp2");
            return (Criteria) this;
        }

        public Criteria andEndIp3IsNull() {
            addCriterion("endIp3 is null");
            return (Criteria) this;
        }

        public Criteria andEndIp3IsNotNull() {
            addCriterion("endIp3 is not null");
            return (Criteria) this;
        }

        public Criteria andEndIp3EqualTo(Integer value) {
            addCriterion("endIp3 =", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3NotEqualTo(Integer value) {
            addCriterion("endIp3 <>", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3GreaterThan(Integer value) {
            addCriterion("endIp3 >", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3GreaterThanOrEqualTo(Integer value) {
            addCriterion("endIp3 >=", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3LessThan(Integer value) {
            addCriterion("endIp3 <", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3LessThanOrEqualTo(Integer value) {
            addCriterion("endIp3 <=", value, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3In(List<Integer> values) {
            addCriterion("endIp3 in", values, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3NotIn(List<Integer> values) {
            addCriterion("endIp3 not in", values, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3Between(Integer value1, Integer value2) {
            addCriterion("endIp3 between", value1, value2, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp3NotBetween(Integer value1, Integer value2) {
            addCriterion("endIp3 not between", value1, value2, "endIp3");
            return (Criteria) this;
        }

        public Criteria andEndIp4IsNull() {
            addCriterion("endIp4 is null");
            return (Criteria) this;
        }

        public Criteria andEndIp4IsNotNull() {
            addCriterion("endIp4 is not null");
            return (Criteria) this;
        }

        public Criteria andEndIp4EqualTo(Integer value) {
            addCriterion("endIp4 =", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4NotEqualTo(Integer value) {
            addCriterion("endIp4 <>", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4GreaterThan(Integer value) {
            addCriterion("endIp4 >", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4GreaterThanOrEqualTo(Integer value) {
            addCriterion("endIp4 >=", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4LessThan(Integer value) {
            addCriterion("endIp4 <", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4LessThanOrEqualTo(Integer value) {
            addCriterion("endIp4 <=", value, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4In(List<Integer> values) {
            addCriterion("endIp4 in", values, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4NotIn(List<Integer> values) {
            addCriterion("endIp4 not in", values, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4Between(Integer value1, Integer value2) {
            addCriterion("endIp4 between", value1, value2, "endIp4");
            return (Criteria) this;
        }

        public Criteria andEndIp4NotBetween(Integer value1, Integer value2) {
            addCriterion("endIp4 not between", value1, value2, "endIp4");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("createBy =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("createBy <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("createBy >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("createBy >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("createBy <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("createBy <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("createBy like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("createBy not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("createBy in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("createBy not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("createBy between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("createBy not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyByIsNull() {
            addCriterion("modifyBy is null");
            return (Criteria) this;
        }

        public Criteria andModifyByIsNotNull() {
            addCriterion("modifyBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifyByEqualTo(String value) {
            addCriterion("modifyBy =", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByNotEqualTo(String value) {
            addCriterion("modifyBy <>", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByGreaterThan(String value) {
            addCriterion("modifyBy >", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByGreaterThanOrEqualTo(String value) {
            addCriterion("modifyBy >=", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByLessThan(String value) {
            addCriterion("modifyBy <", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByLessThanOrEqualTo(String value) {
            addCriterion("modifyBy <=", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByLike(String value) {
            addCriterion("modifyBy like", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByNotLike(String value) {
            addCriterion("modifyBy not like", value, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByIn(List<String> values) {
            addCriterion("modifyBy in", values, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByNotIn(List<String> values) {
            addCriterion("modifyBy not in", values, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByBetween(String value1, String value2) {
            addCriterion("modifyBy between", value1, value2, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyByNotBetween(String value1, String value2) {
            addCriterion("modifyBy not between", value1, value2, "modifyBy");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 25 16:28:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table net_worm_ip_info
     *
     * @mbggenerated Sun Jun 25 16:28:45 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}