package cn.g_open.net_worm.db.model;

import java.util.Date;

public class IpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.id
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.startLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private Long startLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.endLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private Long endLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.location
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.createBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.createDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.modifyBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_info.modifyDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.id
     *
     * @return the value of ip_info.id
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.id
     *
     * @param id the value for ip_info.id
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.startLong
     *
     * @return the value of ip_info.startLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public Long getStartLong() {
        return startLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.startLong
     *
     * @param startLong the value for ip_info.startLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setStartLong(Long startLong) {
        this.startLong = startLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.endLong
     *
     * @return the value of ip_info.endLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public Long getEndLong() {
        return endLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.endLong
     *
     * @param endLong the value for ip_info.endLong
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setEndLong(Long endLong) {
        this.endLong = endLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.location
     *
     * @return the value of ip_info.location
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.location
     *
     * @param location the value for ip_info.location
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.createBy
     *
     * @return the value of ip_info.createBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.createBy
     *
     * @param createBy the value for ip_info.createBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.createDate
     *
     * @return the value of ip_info.createDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.createDate
     *
     * @param createDate the value for ip_info.createDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.modifyBy
     *
     * @return the value of ip_info.modifyBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.modifyBy
     *
     * @param modifyBy the value for ip_info.modifyBy
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_info.modifyDate
     *
     * @return the value of ip_info.modifyDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_info.modifyDate
     *
     * @param modifyDate the value for ip_info.modifyDate
     *
     * @mbggenerated Wed Jun 28 23:21:41 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}